# refs:
# - https://github.com/be5invis/Iosevka#build-your-own-style
# - https://typeof.net/Iosevka

[buildPlans.natasha_I]
family = "Natasha I"
design = [
  # inherit Jetbrains Mono stylistic set
  "ss14",
  # override styles
  "v-underscore-low",
  # customize ligatures
  "calt-center-ops",
  "calt-arrow",
  "calt-trig",
  "calt-eqeq",
  "calt-ineq",
  "calt-exeq",
  "calt-brst",
  "calt-dot-oper",
  "calt-plusplus",
  "calt-kern-dotty",
  "calt-html-comment"
]
